pipeline {
  agent {
    node {
      label 'maven-jdk11'
    }
  }
  stages {
    stage('Git') {
      steps {
        git(url: 'http://git.everylink.ai/paas/chainscan-infra.git', credentialsId: 'gitaccount', changelog: true, poll: false)
      }
    }
    stage('Deploy Snapshot') {
      steps {
        dir('watcher') {
          container('maven-jdk11') {
            sh 'mvn -DskipTests=true package'
            sh 'mvn -DskipTests -Drat.skip=true clean deploy'
          }
        }
      }
    }
  }
}
