pipeline {
  agent {
    node {
      label 'maven-jdk11'
    }
  }

  stages {
    stage('Git') {
      steps {
        git(url: 'http://git.everylink.ai/paas/chainscan-infra.git', credentialsId: 'gitaccount', changelog: true, poll: false)
      }
    }
    stage('Deploy Snapshot') {
      steps {
        dir('watcher/watcher-plugin/watcher-plugin-NFT-auction') {
            container('maven-jdk11') {
                sh 'mvn -DskipTests -Drat.skip=true clean deploy'
            }
        }
      }
    }
  }
}
