apiVersion: apps/v1
kind: Deployment
metadata:
  name: $APP_NAME-production
  namespace: paas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: $APP_NAME-production
  template:
    metadata:
      labels:
        app: $APP_NAME-production
    spec:
      containers:
      - name: $APP_NAME-production
        image:  $REGISTRY/$APP_NAME:SNAPSHOT-$BUILD_NUMBER
        volumeMounts:
        - name: host-time
          mountPath: /etc/localtime
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 7011
        env:
          - name: DB_HOST
            valueFrom:
              secretKeyRef:
                name: database-contribution
                key: url
          - name: DB_PORT
            valueFrom:
              secretKeyRef:
                name: database-contribution
                key: port
          - name: DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: database-contribution
                key: username
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: database-contribution
                key: password
          - name: DB_NAME
            valueFrom:
              secretKeyRef:
                name: database-contribution
                key: db-name
          - name: vmWeb3Url
            valueFrom:
              configMapKeyRef:
                name: watcher-contribution-config
                key: vm-web3-url
        resources:
          requests:
            cpu: 100m
            memory: 1Gi
          limits:
            cpu: '2'
            memory: 4Gi
      volumes:
      - name: host-time
        hostPath:
          path: /etc/localtime
      imagePullSecrets:
      - name: regcred
      restartPolicy: Always
      dnsPolicy: ClusterFirst
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - $APP_NAME-production
              topologyKey: "kubernetes.io/hostname"
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              preference:
                matchExpressions:
                  - key: "eks.amazonaws.com/nodegroup"
                    operator: In
                    values:
                      - "ex-edge"
