apiVersion: apps/v1
kind: Deployment
metadata:
  name: $APP_NAME-production
  namespace: paas
spec:
  replicas: 2
  selector:
    matchLabels:
      app: $APP_NAME-production
  template:
    metadata:
      labels:
        app: $APP_NAME-production
    spec:
      containers:
      - name: $APP_NAME-production
        image:  $REGISTRY/$APP_NAME:SNAPSHOT-$BUILD_NUMBER
        volumeMounts:
        - name: host-time
          mountPath: /etc/localtime
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 7011
        env:
          - name: CHAIN_WS_ENDPOINT
            valueFrom:
              configMapKeyRef:
                name: chainscan-node-config
                key: chain-ws-endpoint
        resources:
          requests:
            cpu: 100m
            memory: 1Gi
          limits:
            cpu: '2'
            memory: 4Gi
      volumes:
      - name: host-time
        hostPath:
          path: /etc/localtime
      imagePullSecrets:
      - name: regcred
      restartPolicy: Always
      dnsPolicy: ClusterFirst
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - $APP_NAME-production
              topologyKey: "kubernetes.io/hostname"
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              preference:
                matchExpressions:
                  - key: "eks.amazonaws.com/nodegroup"
                    operator: In
                    values:
                      - "ex-edge"
