apiVersion: v1
kind: Service
metadata:
  name: $APP_NAME-production
  namespace: paas
spec:
  ports:
  - name: http
    port: 7010
    targetPort: 7010
    protocol: TCP
  selector:
    app: $APP_NAME-production
  sessionAffinity: None
  type: ClusterIP
