apiVersion: apps/v1
kind: Deployment
metadata:
  name: $APP_NAME-sandbox
  namespace: paas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: $APP_NAME-sandbox
  template:
    metadata:
      labels:
        app: $APP_NAME-sandbox
    spec:
      containers:
      - name: $APP_NAME-sandbox
        image:  $REGISTRY/$APP_NAME:SNAPSHOT-$BUILD_NUMBER
        volumeMounts:
        - name: host-time
          mountPath: /etc/localtime
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh", "-c", "--"]
        args: ["while true; do npm run start; sleep 30; done;"]
        ports:
        - containerPort: 7011
        env:
          - name: CHAIN_WS_ENDPOINT
            valueFrom:
              configMapKeyRef:
                name: chainscan-config
                key: chain-ws-endpoint
        resources:
          requests:
            cpu: 100m
            memory: 1Gi
          limits:
            cpu: '2'
            memory: 4Gi
      volumes:
      - name: host-time
        hostPath:
          path: /etc/localtime
      imagePullSecrets:
      - name: regcred
      restartPolicy: Always
      dnsPolicy: ClusterFirst
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - $APP_NAME-sandbox
              topologyKey: "kubernetes.io/hostname"
