apiVersion: apps/v1
kind: Deployment
metadata:
  name: $APP_NAME-sandbox
  namespace: paas
spec:
  replicas: 2
  selector:
    matchLabels:
      app: $APP_NAME-sandbox
  template:
    metadata:
      labels:
        app: $APP_NAME-sandbox
    spec:
      containers:
      - name: $APP_NAME-sandbox
        image:  $REGISTRY/$APP_NAME:SNAPSHOT-$BUILD_NUMBER
        volumeMounts:
        - name: host-time
          mountPath: /etc/localtime
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh", "-c", "--"]
        args: ["while true; do npm run start; sleep 30; done;"]
        ports:
        - containerPort: 7010
        env:
          - name: CDN_HOST
            valueFrom:
              configMapKeyRef:
                name: chainscan-backend-config
                key: cdn-host
          - name: TZ
            value: GMT
          - name: NODE_ENV
            value: "sandbox"
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: database-chainscan
                key: password
          - name: DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: database-chainscan
                key: username
          - name: DB_HOST
            valueFrom:
              secretKeyRef:
                name: database-chainscan
                key: db-host
          - name: DB_PORT
            valueFrom:
              secretKeyRef:
                name: database-chainscan
                key: db-port
          - name: DB_NAME
            valueFrom:
              secretKeyRef:
                name: database-chainscan
                key: db-name
        resources:
          requests:
            cpu: 0.1
            memory: 0.1Gi
          limits:
            cpu: 1
            memory: 0.5Gi
      volumes:
      - name: host-time
        hostPath:
          path: /etc/localtime
      imagePullSecrets:
      - name: regcred
      restartPolicy: Always
      dnsPolicy: ClusterFirst
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - $APP_NAME-sandbox
              topologyKey: "kubernetes.io/hostname"
