apiVersion: v1
kind: Service
metadata:
  name: $APP_NAME-sandbox
  namespace: paas
spec:
  ports:
  - name: http
    port: 7010
    targetPort: 7010
    protocol: TCP
#    nodePort: 31296
  selector:
    app: $APP_NAME-sandbox
  sessionAffinity: None
#  type: NodePort
  type: ClusterIP
