apiVersion: apps/v1
kind: Deployment
metadata:
  name: $APP_NAME-sandbox
  namespace: paas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: $APP_NAME-sandbox
  template:
    metadata:
      labels:
        app: $APP_NAME-sandbox
    spec:
      containers:
      - name: $APP_NAME-sandbox
        image:  $REGISTRY/$APP_NAME:SNAPSHOT-$BUILD_NUMBER
        volumeMounts:
        - name: host-time
          mountPath: /etc/localtime
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 7011
        env:
          - name: DB_HOST
            valueFrom:
              configMapKeyRef:
                name: watcher-contribution-config
                key: db-host
          - name: DB_PORT
            valueFrom:
              configMapKeyRef:
                name: watcher-contribution-config
                key: db-port
          - name: DB_USERNAME
            valueFrom:
              configMapKeyRef:
                name: watcher-contribution-config
                key: db-username
          - name: DB_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: watcher-contribution-config
                key: db-password
          - name: DB_NAME
            valueFrom:
              configMapKeyRef:
                name: watcher-contribution-config
                key: db-name
          - name: vmWeb3Url
            valueFrom:
              configMapKeyRef:
                name: watcher-contribution-config
                key: vm-web3-url
          - name: ethWeb3Url
            valueFrom:
              configMapKeyRef:
                name: watcher-contribution-config
                key: eth-web3-url
          - name: feeAccountPrivateKey
            valueFrom:
              configMapKeyRef:
                name: watcher-contribution-config
                key: fee-account-private-key
        resources:
          requests:
            cpu: 100m
            memory: 1Gi
          limits:
            cpu: '2'
            memory: 4Gi
      volumes:
      - name: host-time
        hostPath:
          path: /etc/localtime
      imagePullSecrets:
      - name: regcred
      restartPolicy: Always
      dnsPolicy: ClusterFirst
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - $APP_NAME-sandbox
              topologyKey: "kubernetes.io/hostname"
